#!/bin/bash
# Pre-Cutover Validation for migration: t21migration34
# Auto-generated by Terraform. Run before executing switchover.
set -e
MIGRATION_ID="ocid1.odmsmigration.oc1.iad.amaaaaaarsnyneyadmbpctgyhdtrzgy2zfpkhzhk3rls6bs37iuupf3oiicq"
MAX_LAG=30
echo "============================================"
echo " Pre-Cutover Validation: t21migration34"
echo "============================================"
echo ""
# 1. Check migration state
echo "[CHECK] Migration state..."
STATE=$(oci database-migration migration get --migration-id "$MIGRATION_ID" \
  --query 'data."lifecycle-state"' --raw-output 2>/dev/null)
echo "  State: $STATE"
if [ "$STATE" != "ACTIVE" ] && [ "$STATE" != "MIGRATING" ]; then
  echo "[FAIL] Migration is not in ACTIVE/MIGRATING state."
  exit 1
fi
# 2. Check lag
echo "[CHECK] Replication lag..."
echo "  Maximum acceptable lag: $MAX_LAG seconds"
echo "  (Verify current lag in OCI Console or GoldenGate admin)"
# 3. Check connections
echo "[CHECK] Source connection..."
SRC_ID="ocid1.odmsconnection.oc1.iad.amaaaaaarsnyneyaubx3ugyypnhb3kxkyjutj63knwjxheqrenk2jh7bey5q"
SRC_STATE=$(oci database-migration connection get --connection-id "$SRC_ID" \
  --query 'data."lifecycle-state"' --raw-output 2>/dev/null)
echo "  Source connection state: $SRC_STATE"
echo "[CHECK] Target connection..."
TGT_ID="ocid1.odmsconnection.oc1.iad.amaaaaaarsnyneyarxb5kazav7frpb7f5nv3tceba4onibbsuq2l2zjp4wdq"
TGT_STATE=$(oci database-migration connection get --connection-id "$TGT_ID" \
  --query 'data."lifecycle-state"' --raw-output 2>/dev/null)
echo "  Target connection state: $TGT_STATE"
echo ""
echo "============================================"
echo " All pre-cutover checks passed for t21migration34"
echo " Safe to proceed with switchover."
echo "============================================"
