-- GoldenGate Extract Parameter File
-- Auto-generated by Terraform
EXTRACT ${extract_name}
USERIDALIAS ${source_db_alias} DOMAIN OracleGoldenGate
EXTTRAIL ${trail_name}

-- Extract type
%{ if extract_type == "INTEGRATED" ~}
TRANLOGOPTIONS INTEGRATEDPARAMS (MAX_SGA_SIZE 256)
%{ endif ~}

-- Schema mappings
%{ for schema in schemas_to_extract ~}
TABLE ${schema}.*;
%{ endfor ~}

-- Exclusions
%{ for excl in exclude_tables ~}
TABLEEXCLUDE ${excl};
%{ endfor ~}

-- Performance
WARNLONGTRANS 1H, CHECKINTERVAL 30M
CACHEMGR CACHESIZE 512MB
FETCHOPTIONS FETCHPKUPDATECOLS
