-- GoldenGate Replicat Parameter File
-- Auto-generated by Terraform
REPLICAT ${replicat_name}
USERIDALIAS ${target_db_alias} DOMAIN OracleGoldenGate

%{ if replicat_type == "PARALLEL" ~}
-- Parallel Replicat
MAP_PARALLELISM ${map_parallelism}
%{ if bulk_applies ~}
BATCHSQL BATCHTRANSOPS 1000
%{ endif ~}
%{ endif ~}

-- Schema mappings
%{ for schema in schemas_to_replicate ~}
MAP ${schema}.*, TARGET ${schema}.*;
%{ endfor ~}

-- Exclusions
%{ for excl in exclude_tables ~}
MAPEXCLUDE ${excl};
%{ endfor ~}

-- Error handling
REPERROR (DEFAULT, EXCEPTION)
HANDLECOLLISIONS
