--                                                                                                                                                                                                                                                                                                          
-- The output shown below is informational. This is to provide you detail on the actions                                                                                                                                                                                                                    
-- that will be performed when the generated script is ran on your database.                                                                                                                                                                                                                                
--                                                                                                                                                                                                                                                                                                          
--                                                                                                                                                                                                                                                                                                          
--########################################################################################                                                                                                                                                                                                                  
--          Database Information                                                                                                                                                                                                                                                                            
--########################################################################################                                                                                                                                                                                                                  
--Database Name:                CA49ZIVXDXWCY4WX                                                                                                                                                                                                                                                            
--Database Version:             23.0.0.0                                                                                                                                                                                                                                                                    
--Database User:                YES   (User Name:  GGADMIN)                                                                                                                                                                                                                                                 
--Database User locked:         YES   (Required: NO)                                                                                                                                                                                                                                                        
--Database Global Names:        FALSE                                                                                                                                                                                                                                                                       
--                                                                                                                                                                                                                                                                                                          
--########################################################################################                                                                                                                                                                                                                  
--   Actions to be performed for preparing your TARGET Database for ONLINE Migration                                                                                                                                                                                                                        
--########################################################################################                                                                                                                                                                                                                  
--                                                                                                                                                                                                                                                                                                          
-- Global_names is set to FALSE, NO action required.                                                                                                                                                                                                                                                        
--                                                                                                                                                                                                                                                                                                          
-- User SYSTEM (Initial Load User) from database CA49ZIVXDXWCY4WX is locked, alter user account unlock is required.                                                                                                                                                                                         
--                                                                                                                                                                                                                                                                                                          
-- For the migration, a user that has the DATAPUMP_EXP_FULL_DATABASE role is required for the                                                                                                                                                                                                               
-- export operation at the source database.  This user is  selected as database administrator                                                                                                                                                                                                               
-- when you create  Database Connections with the source databases.  Oracle DMS recommends to                                                                                                                                                                                                               
-- utilize the system user.                                                                                                                                                                                                                                                                                 
--                                                                                                                                                                                                                                                                                                          
ALTER USER SYSTEM IDENTIFIED BY "dummy" ACCOUNT UNLOCK;                                                                                                                                                                                                                                                     
--                                                                                                                                                                                                                                                                                                          
--                                                                                                                                                                                                                                                                                                          
--###########################################################                                                                                                                                                                                                                                               
--#### Privileges to be granted to the Initial Load user ####                                                                                                                                                                                                                                               
--###########################################################                                                                                                                                                                                                                                               
--                                                                                                                                                                                                                                                                                                          
GRANT CREATE SESSION TO SYSTEM;                                                                                                                                                                                                                                                                             
GRANT DATAPUMP_EXP_FULL_DATABASE TO SYSTEM;                                                                                                                                                                                                                                                                 
GRANT DATAPUMP_IMP_FULL_DATABASE TO SYSTEM;                                                                                                                                                                                                                                                                 
GRANT SELECT ANY DICTIONARY TO SYSTEM;                                                                                                                                                                                                                                                                      
GRANT EXECUTE ON UTL_HTTP TO SYSTEM;                                                                                                                                                                                                                                                                        
--                                                                                                                                                                                                                                                                                                          
--                                                                                                                                                                                                                                                                                                          
--##########################################################                                                                                                                                                                                                                                                
--#### Unlock and Grant Privileges to the NonCDB user. ####                                                                                                                                                                                                                                                 
--##########################################################                                                                                                                                                                                                                                                
--                                                                                                                                                                                                                                                                                                          
-- GoldenGate User already exists but is locked, alter user required.                                                                                                                                                                                                                                       
--                                                                                                                                                                                                                                                                                                          
ALTER USER GGADMIN IDENTIFIED BY "A_miN123#_ADB" ACCOUNT UNLOCK;                                                                                                                                                                                                                                            
--                                                                                                                                                                                                                                                                                                          
--##########################################################                                                                                                                                                                                                                                                
--#### Privileges to be granted to the GoldenGate user. ####                                                                                                                                                                                                                                                
--##########################################################                                                                                                                                                                                                                                                
--                                                                                                                                                                                                                                                                                                          
GRANT PDB_DBA TO GGADMIN WITH ADMIN OPTION;                                                                                                                                                                                                                                                                 
--                                                                                                                                                                                                                                                                                                          
-- Script DMS_Configuration.sql generated. Please review this script, modify as appropriate and run it in your database.                                                                                                                                                                                    
-- Your target database will be ready for migration after execution of these operations.                                                                                                                                                                                                                    
--                                                                                                                                                                                                                                                                                                          
